### ISSUE TITLE
gnocchi client help output broken in python 2 due to unicode character

### ISSUE THREAD

**Issue by cristicalin** [gnocchixyz/python-gnocchiclient#15]
Example: https://github.com/gnocchixyz/python-gnocchiclient/blob/master/gnocchiclient/v1/resource_type_cli.py#L48
 
The display of \u2026 unicode character is broken by default in python2.

```
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> s=u"\u2026"
>>> print s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 0: ordinal not in range(128)
```

From the gnocchi client itself:
```
$ gnocchi --insecure help resource-type update
'ascii' codec can't encode character u'\u2026' in position 772: ordinal not in range(128)
```

This can be easily fixed by replacing \u2026 with the ascii representation: "..." (3 dots)

**Comment by jd** [comment]
Really depends on your locale I guess. What is it?

```
➔ python
Python 2.7.13 (default, Mar 17 2017, 16:14:42)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> s=u"\u2026"
>>> print s
…
```

**Comment by cristicalin** [comment]
I don't have any locale configured, so I guess the default is "C".

I explicitly set the locale to "C" which is what you get on minimal ubuntu/centos installs anyway. And I get the same broken behaviour:

```
[kman:~] $ export LOCALE=C
[kman:~] $ export LC_ALL=C
[kman:~] $ export LANG=en_US.UTF-8
[kman:~] $ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> s=u'\u2026'
>>> print s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 0: ordinal not in range(128)
```

**Comment by cristicalin** [comment]
Closing, resolved.
