### ISSUE TITLE
"gnocchi measures add ..." failed, it seems to be about ceph

### ISSUE THREAD

**Issue by yjLiInSky** [gnocchixyz/python-gnocchiclient#55]
i choose ceph as backend for gnocchi and install it. It can get the resource list and metric list. But when i try to manually add measures to a metric. It failed, it show this "Unable to establish connection to http://172.21.195.20:8041/v1/metric/cad328db-966e-46fd-9c5b-ecb65cbef915/measures: ('Connection aborted.', BadStatusLine("''",))".

And  in /var/log/gnocchi/gnocchi-api.log :
  2017-10-25 20:00:39,809 [9390] CRITICAL root: Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 131, in __call__
     resp = self.call_func(req, *args, **self.kwargs)
   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 196, in call_func
    return self.func(req, *args, **kwargs)
   File "/usr/lib/python2.7/site-packages/oslo_middleware/base.py", line 131, in __call__
     response = req.get_response(self.application)
   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1316, in send
     application, catch_exc_info=False)
   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1280, in call_application
    app_iter = application(self.environ, start_response)
   File "/usr/lib/python2.7/site-packages/paste/urlmap.py", line 216, in __call__
     return app(environ, start_response)
   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 131, in __call__
     resp = self.call_func(req, *args, **self.kwargs)
   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 196, in call_func
     return self.func(req, *args, **kwargs)
   File "/usr/lib/python2.7/site-packages/oslo_middleware/base.py", line 131, in __call__
     response = req.get_response(self.application)
   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1316, in send
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1280, in call_application
     app_iter = application(self.environ, start_response)
   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 131, in __call__
     resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/webob/dec.py", line 196, in call_func
    return self.func(req, *args, **kwargs)
   File "/usr/lib/python2.7/site-packages/keystonemiddleware/auth_token/__init__.py", line 334, in __call__
     response = req.get_response(self._app)
   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1316, in send
     application, catch_exc_info=False)
   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1280, in call_application
     app_iter = application(self.environ, start_response)
   File "/usr/lib/python2.7/site-packages/webob/exc.py", line 1162, in __call__
     return self.application(environ, start_response)
  File "/home/yjli/gnocchi/gnocchi/rest/app.py", line 70, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/pecan/middleware/recursive.py", line 56, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.7/site-packages/pecan/core.py", line 840, in __call__
    return super(Pecan, self).__call__(environ, start_response)
  File "/usr/lib/python2.7/site-packages/pecan/core.py", line 683, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/usr/lib/python2.7/site-packages/pecan/core.py", line 574, in invoke_controller
    result = controller(*args, **kwargs)
  File "/home/yjli/gnocchi/gnocchi/rest/api.py", line 1561, in post
    for metric in known_metrics))
  File "/home/yjli/gnocchi/gnocchi/incoming/ceph.py", line 105, in add_measures_batch
    ops.append(self.ioctx.operate_aio_write_op(
AttributeError: 'rados.Ioctx' object has no attribute 'operate_aio_write_op'.

What causes this? Does anyone have a solution? Thanks.

**Comment by jd** [comment]
Did you respect the Ceph dependency listed here:
http://gnocchi.xyz/install.html#id1

because it looks like you have an old version of the Ceph bindings.

**Comment by yjLiInSky** [comment]
the ceph version is 10.2.10

**Comment by chungg** [comment]
referring to: https://github.com/gnocchixyz/gnocchi/blob/master/setup.cfg#L43-L46

```
ceph_recommended_lib =
    cradox>=1.2.0
ceph_alternative_lib =
    python-rados>=12.2.0 # not available on pypi
```
